mybatis:
  type-aliases-package: "com.zs.ecms.pojo"

server:
  port: 8080


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/dubbo?characterEncoding=utf8&useSSL=false&serverTimezone=GMT&allowMultiQueries=true"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    data-username: "root"
    data-password: "root"
